export const CNAE_SEGMENT_MAP: Record<string, string> = {
  "01": "Agropecuária",
  "02": "Agropecuária",
  "03": "Pesca / Aquicultura",
  "05": "Indústria Extrativa",
  "06": "Indústria Extrativa",
  "07": "Indústria Extrativa",
  "08": "Indústria Extrativa",
  "09": "Indústria Extrativa",
  "10": "Indústria de Alimentos",
  "11": "Indústria de Bebidas",
  "12": "Indústria de Tabaco",
  "13": "Indústria Têxtil",
  "14": "Indústria de Vestuário",
  "15": "Indústria de Couro/Calçados",
  "16": "Indústria de Madeira",
  "17": "Indústria de Papel",
  "18": "Indústria Gráfica",
  "19": "Indústria de Combustíveis",
  "20": "Indústria Química",
  "21": "Indústria Farmacêutica",
  "22": "Indústria de Plásticos/Borracha",
  "23": "Indústria de Minerais",
  "24": "Indústria Metalúrgica",
  "25": "Indústria Metalúrgica",
  "26": "Eletroeletrônicos",
  "27": "Máquinas/Equipamentos Elétricos",
  "28": "Máquinas/Equipamentos",
  "29": "Indústria Automotiva",
  "30": "Indústria de Transporte",
  "31": "Indústria de Móveis",
  "32": "Indústria Diversa",
  "33": "Manutenção/Reparação",
  "35": "Energia Elétrica/Gás",
  "36": "Saneamento",
  "37": "Saneamento",
  "38": "Resíduos / Reciclagem",
  "39": "Descontaminação",
  "41": "Construção Civil",
  "42": "Construção Civil",
  "43": "Construção Civil",
  "45": "Comércio de Veículos",
  "46": "Comércio Atacadista",
  "47": "Comércio Varejista",
  "49": "Transporte Terrestre",
  "50": "Transporte Aquaviário",
  "51": "Transporte Aéreo",
  "52": "Armazenamento/Logística",
  "53": "Correio/Encomendas",
  "55": "Hotelaria",
  "56": "Alimentação Fora do Lar",
  "58": "Mídia / Editoras",
  "59": "Áudio/Vídeo",
  "60": "Rádio/TV",
  "61": "Telecomunicações",
  "62": "Tecnologia da Informação",
  "63": "TI / Dados",
  "64": "Serviços Financeiros",
  "65": "Seguros",
  "66": "Serviços Financeiros Auxiliares",
  "68": "Mercado Imobiliário",
  "69": "Jurídico/Contábil",
  "70": "Consultoria/Gestão",
  "71": "Engenharia/Arquitetura",
  "72": "Pesquisa e Desenvolvimento",
  "73": "Publicidade/Marketing",
  "74": "Serviços Técnicos",
  "75": "Veterinária",
  "77": "Aluguel/Leasing",
  "78": "Recursos Humanos",
  "79": "Turismo/Agências",
  "80": "Segurança",
  "81": "Serviços a Edifícios",
  "82": "Serviços Administrativos",
  "84": "Administração Pública",
  "85": "Educação",
  "86": "Saúde",
  "87": "Saúde / Assistência",
  "88": "Assistência Social",
  "90": "Artes/Cultura",
  "91": "Patrimônio Cultural",
  "92": "Jogos/Apostas",
  "93": "Esporte/Lazer",
  "94": "Organizações Associativas",
  "95": "Reparação Doméstica",
  "96": "Serviços Pessoais",
  "97": "Serviços Domésticos",
  "99": "Organismos Internacionais",
};
